# Site settings
title: HanaHaus
email: hassan.khan@sap.com
description: > #
  A new café experience where creative individuals
  and entrepreneurs can come together to meet, socialize, 
  share ideas and connect with experts.
baseurl: "/HanaHaus-app" # the subpath of your site, e.g. /blog/
url: "http://hanahaus.com" # the base hostname & protocol for your site
twitter_username: HanaHaus
github_username:  HanaHaus

# Build settings
markdown: kramdown

# Exclude npm/grunt/bower files
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/javascripts/vendor
